import html
import itertools
import re

import gradio as gr

from shared.gradio import model_infos


_COUNTER = itertools.count()


SYSTEM_HELP = {
    "spatial_upsampling": {
        "title": "Spatial Upsampling",
        "markdown": """
Spatial Upsampling increases the output resolution of the Image / Video by the Scale Factor that has been chosen. New Pixels created will depend on the upsampling method:

### Lanczos
- Works: images and videos, generation and late postprocessing.
- Speed: very fast CPU resize.
- Memory: tiny VRAM impact, low RAM use.
- Quality: sharper than a basic resize, but may add ringing/aliasing, won't extrapolate lost details

### VAE Upscaling
- Works: generation-time images usable only with Wan / QWen.
- Speed: no extra time since it runs through the existing VAE path.
- Memory: VRAM peak is mostly uneffected.
- Quality: more details than Lanczos but quality of created details worse than PiD/FlashVSR.
- Caveat: image-only, not available as late postprocessing.

### FlashVSR
- Works: videos and images, generation and late postprocessing.
- Speed: may be very slow in its final VAE decoding phase with Full version (pick Tiny version in configuration tab for faster performance).
- Memory: quite well RAM/VRAM optimized but may saturate VRAM if output > 10k.
- Quality: learned detail recovery with good video temporal stability. Two Pass may reduce horizontal banding
- Caveat: requires SpargeAttn to be installed for best results.

### Flux / Flux2 VAE PiD
- Works: images generated by a compatible Flux, Flux2, or Z-Image pipeline. Upsampler directly integrated in VAE.
- Speed: runs a dedicated x4 diffusion upsampler can be quite slow if image input has already a high resolution.
- Memory: moderate VRAM/RAM use, but avoids VAE re-encoding because the latent already exists.
- Quality: strongest detail recovery since the matching latent is available.
- Caveat: image-only and x4 only.

### Flux / Flux2 PiD
- Works: existing images in late postprocessing.
- Speed: slightly slower since VAE-encodes first, then runs PiD.
- Memory: high RAM/VRAM use; tiling reduces VRAM peaks for large targets.
- Quality: strong detail recovery but some slight information may be loss due to VAE encoding
- Caveat: image-only and x4 only.
""",
    },
}


def get_model_prompt_help(model_def):
    model_def = model_def or {}
    return model_def.get("prompt_infos", model_def.get("promt_infos", None))


def _normalize_classes(value):
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


def _ensure_component_target(component):
    elem_id = getattr(component, "elem_id", None)
    if not elem_id:
        elem_id = f"wangp-field-help-target-{next(_COUNTER)}"
        component.elem_id = elem_id
    classes = _normalize_classes(getattr(component, "elem_classes", None))
    if "wangp-field-help-target" not in classes:
        classes.append("wangp-field-help-target")
        component.elem_classes = classes
    return elem_id


def _resolve_help(help_id, *, title=None, markdown=None):
    if markdown is not None:
        return title or "Help", str(markdown)
    help_def = SYSTEM_HELP.get(str(help_id or ""))
    if isinstance(help_def, dict):
        return title or help_def.get("title", "Help"), str(help_def.get("markdown", ""))
    return title or "Help", str(help_def or "")


def render_marker(elem_id, help_id, *, title=None, markdown=None):
    title, markdown = _resolve_help(help_id, title=title, markdown=markdown)
    if not str(markdown or "").strip():
        return ""
    popup_key = re.sub(r"[^A-Za-z0-9_-]", "-", f"{elem_id}-{help_id}").strip("-").lower()
    popup_id = f"wangp-field-help-{popup_key}"
    return (
        f"<div class='wangp-field-help-marker' data-wangp-field-help-for='{html.escape(elem_id, quote=True)}' "
        f"data-wangp-field-help-popup='{html.escape(popup_id, quote=True)}' data-wangp-field-help-title='{html.escape(title, quote=True)}'>"
        f"{model_infos.render_info_popup(popup_id, title, markdown, lazy=True)}"
        "</div>"
    )


def bind(component, help_id, *, title=None, markdown=None):
    elem_id = _ensure_component_target(component)
    marker = render_marker(elem_id, help_id, title=title, markdown=markdown)
    if not marker:
        return gr.HTML("", visible=False)
    return gr.HTML(marker, elem_classes=["wangp-field-help-marker-host"])


def render_model_prompt_marker(elem_id, model_type, model_def, prompt_id):
    infos = get_model_prompt_help(model_def)
    if isinstance(infos, (list, tuple)) and len(infos) >= 2:
        title, markdown = str(infos[0] or "Prompt Guidelines"), str(infos[1] or "")
    else:
        title, markdown = "Prompt Guidelines", str(infos or "")
    return render_marker(elem_id, f"prompt-{model_type or 'model'}-{prompt_id or 'prompt'}", title=title, markdown=markdown)


def get_css():
    return """
.wangp-field-help-marker-host,
.wangp-field-help-marker {
    display: none !important;
}
.wangp-field-help-trigger {
    position: static !important;
    display: inline-flex !important;
    align-items: center;
    justify-content: center;
    width: 18px !important;
    height: 18px !important;
    min-width: 18px !important;
    min-height: 18px !important;
    padding: 0 !important;
    margin: 0 0 0 6px !important;
    border: 1px solid var(--button-secondary-border-color, rgba(17, 84, 118, 0.24)) !important;
    border-radius: 999px !important;
    background: var(--button-secondary-background-fill, rgba(255, 255, 255, 0.86)) !important;
    color: var(--button-secondary-text-color, #155574) !important;
    box-shadow: none !important;
    cursor: pointer;
    vertical-align: middle;
    font-size: 11px !important;
    line-height: 1 !important;
    opacity: 1 !important;
    visibility: visible !important;
}
"""


def get_javascript():
    return """
    window.wangpFieldHelp = window.wangpFieldHelp || {};
    window.wangpFieldHelp.findLabel = function(target) {
        if (!target) return null;
        var blockInfo = target.querySelector('[data-testid="block-info"]');
        if (blockInfo) return blockInfo;
        var label = target.querySelector("label");
        if (label) return label;
        return null;
    };
    window.wangpFieldHelp.hasTrigger = function(label, popupId) {
        var triggers = label.querySelectorAll("[data-wangp-field-help-trigger]");
        for (var i = 0; i < triggers.length; i++) {
            if (triggers[i].getAttribute("data-wangp-field-help-trigger") === popupId) return true;
        }
        return false;
    };
    window.wangpFieldHelp.collectActivePopups = function(markers) {
        var activePopups = {};
        markers.forEach(function(marker) {
            var popupId = marker.getAttribute("data-wangp-field-help-popup");
            if (popupId) activePopups[popupId] = true;
        });
        return activePopups;
    };
    window.wangpFieldHelp.cleanupStaleTriggers = function(activePopups) {
        document.querySelectorAll("[data-wangp-field-help-trigger]").forEach(function(trigger) {
            var popupId = trigger.getAttribute("data-wangp-field-help-trigger");
            if (!popupId || !activePopups[popupId]) trigger.remove();
        });
        document.querySelectorAll('[data-wangp-model-info-popup][id^="wangp-field-help-"]').forEach(function(popup) {
            if (!activePopups[popup.id]) popup.remove();
        });
    };
    window.wangpFieldHelp.attach = function() {
        var markers = document.querySelectorAll("[data-wangp-field-help-for]");
        var activePopups = window.wangpFieldHelp.collectActivePopups(markers);
        window.wangpFieldHelp.cleanupStaleTriggers(activePopups);
        markers.forEach(function(marker) {
            var targetId = marker.getAttribute("data-wangp-field-help-for");
            var popupId = marker.getAttribute("data-wangp-field-help-popup");
            var title = marker.getAttribute("data-wangp-field-help-title") || "Help";
            var popup = popupId ? document.getElementById(popupId) : null;
            if (popup && popup.parentElement !== document.body) document.body.appendChild(popup);
            var target = targetId ? document.getElementById(targetId) : null;
            var label = window.wangpFieldHelp.findLabel(target);
            if (!label || !popupId || window.wangpFieldHelp.hasTrigger(label, popupId)) return;
            var labelTarget = label.matches && label.matches('[data-testid="block-info"]') ? label : (label.querySelector("span") || label);
            var button = document.createElement("button");
            button.type = "button";
            button.className = "wangp-field-help-trigger";
            button.title = title;
            button.setAttribute("aria-label", title);
            button.setAttribute("data-wangp-model-info-open", popupId);
            button.setAttribute("data-wangp-field-help-trigger", popupId);
            button.innerHTML = "&#9432;";
            labelTarget.appendChild(button);
        });
    };
    window.wangpFieldHelp.start = function() {
        window.wangpFieldHelp.attach();
        if (!window.wangpFieldHelp.observer && document.body) {
            window.wangpFieldHelp.observer = new MutationObserver(window.wangpFieldHelp.attach);
            window.wangpFieldHelp.observer.observe(document.body, { childList: true, subtree: true });
        }
    };
    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", window.wangpFieldHelp.start);
    } else {
        window.wangpFieldHelp.start();
    }
    window.addEventListener("load", window.wangpFieldHelp.start);
    setTimeout(window.wangpFieldHelp.start, 250);
    setTimeout(window.wangpFieldHelp.start, 1200);
"""
